spring:
  application:
    name: jobapplication
  datasource:
    url: jdbc:postgresql://ep-square-haze-zahv1klg-pooler.c-2.eu-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_nvUmBGk5Y9bT
  jpa:
    hibernate:
      ddl-auto: update
